### ISSUE TITLE
Adding the mod to an existing game causes trains to be damaged and get stuck

### ISSUE THREAD

**Issue by jvanegmond** [Jackalope-Gaming/8L-Train-Project#3]
- Play the game without mods up until trains, tracks, signals, etc.
- Add the 8L train project mod.
- Existing trains spawned before adding the mod can get stuck and damaged in corners.

The locomotive or any of the wagons behind it can be damaged and this causes the train to be stuck. Eventually the train will destroy itself or one of its wagons and proceed on its assigned course.

See attached screenshot:
![image](https://cloud.githubusercontent.com/assets/4513254/14402963/ecc0ae60-fe44-11e5-8579-095d2e4fbff6.png)

Factorio version 0.12.29
Mod version 8L-Train-Project_1.2.1

**Comment by Jackalope-Gaming** [comment]
At the moment all of the train entities need to be manually picked up and placed down again for the distance between entities to be fixed and thus not cause that problem.  If there is some sort of scripting I can implement to force them to spread out to their proper modded lengths then I will do so, but I'm not aware of such scripting yet.
